version: '3.5'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=adzia
      - SPRING_DATASOURCE_PASSWORD=adzia
    networks:
      - proxynet
    depends_on:
      - db

  db:
    image: mysql/mysql-server:8.0
    restart: always
    networks:
      - proxynet
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'adzia'
      MYSQL_PASSWORD: 'adzia'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:

networks:
  proxynet:
    name: custom_network